name: geolearn
description: "A new Flutter project."

# Impede que o pacote seja publicado acidentalmente no pub.dev
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

# Define a versão e o número de build do projeto
version: 1.0.0+1

# Define o ambiente e a versão mínima do SDK
environment:
  sdk: ^3.6.0

# Dependências principais do projeto
dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  translator: 1.0.3+1

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recomendações de lint para boas práticas
  flutter_lints: ^5.0.0

# Configuração específica do Flutter
flutter:
  uses-material-design: true # Habilita ícones padrão do Material Design

  # Seção de assets (imagens e outros arquivos)
  assets:
    - assets/images/terra.png
    - assets/images/mountain.png
    - assets/images/paises.png
    - assets/images/bandeiras.png
    - assets/images/estados.png

  # Exemplo comentado para adicionar fontes personalizadas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
