name: geolearn
description: "A new Flutter project."

# Impede que o pacote seja publicado acidentalmente no pub.dev
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

# Define a versão e o número de build do projeto
version: 1.0.0+1

# Define o ambiente e a versão mínima do SDK
environment:
  sdk: ^3.6.0

# Dependências principais do projeto
dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  translator: 1.0.3+1
  audioplayers: ^6.1.2

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recomendações de lint para boas práticas
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Correção aqui!

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Caminho da sua imagem

# Configuração específica do Flutter
flutter:
  uses-material-design: true # Habilita ícones padrão do Material Design

  # Seção de assets (imagens e outros arquivos)
  assets:
    - assets/images/terra.png
    - assets/images/mountain.png
    - assets/images/paises.png
    - assets/images/bandeiras.png
    - assets/images/estados.png
    - assets/images/brasil.png
    - assets/images/estados-unidos.png
    - assets/images/alemanha.png
    # Assets dos estados Brasileiros
    - assets/images/flagsbr/ac.png
    - assets/images/flagsbr/al.png
    - assets/images/flagsbr/ap.png
    - assets/images/flagsbr/am.png
    - assets/images/flagsbr/bh.png
    - assets/images/flagsbr/ce.png
    - assets/images/flagsbr/df.png
    - assets/images/flagsbr/es.png
    - assets/images/flagsbr/go.png
    - assets/images/flagsbr/ma.png
    - assets/images/flagsbr/mt.png
    - assets/images/flagsbr/mg.png
    - assets/images/flagsbr/pa.png
    - assets/images/flagsbr/pb.png
    - assets/images/flagsbr/pr.png
    - assets/images/flagsbr/pe.png
    - assets/images/flagsbr/pi.png
    - assets/images/flagsbr/rj.png
    - assets/images/flagsbr/rn.png
    - assets/images/flagsbr/rs.png
    - assets/images/flagsbr/ro.png
    - assets/images/flagsbr/rr.png
    - assets/images/flagsbr/sc.png
    - assets/images/flagsbr/sp.png
    - assets/images/flagsbr/se.png
    - assets/images/flagsbr/to.png
    # Assets dos estados Alemães
    - assets/images/flagsal/bw.png
    - assets/images/flagsal/by.png
    - assets/images/flagsal/be.png
    - assets/images/flagsal/bb.png
    - assets/images/flagsal/hb.png
    - assets/images/flagsal/hh.png
    - assets/images/flagsal/he.png
    - assets/images/flagsal/mv.png
    - assets/images/flagsal/ni.png
    - assets/images/flagsal/nw.png
    - assets/images/flagsal/rp.png
    - assets/images/flagsal/sl.png
    - assets/images/flagsal/sn.png
    - assets/images/flagsal/st.png
    - assets/images/flagsal/sh.png
    - assets/images/flagsal/th.png
    # Assets dos estados Estadunidenses
    - assets/images/flagusa/al.png
    - assets/images/flagusa/ak.png
    - assets/images/flagusa/az.png
    - assets/images/flagusa/ar.png
    - assets/images/flagusa/ca.png
    - assets/images/flagusa/co.png
    - assets/images/flagusa/ct.png
    - assets/images/flagusa/de.png
    - assets/images/flagusa/fl.png
    - assets/images/flagusa/ga.png
    - assets/images/flagusa/hi.png
    - assets/images/flagusa/id.png
    - assets/images/flagusa/il.png
    - assets/images/flagusa/in.png
    - assets/images/flagusa/ia.png
    - assets/images/flagusa/ks.png
    - assets/images/flagusa/ky.png
    - assets/images/flagusa/la.png
    - assets/images/flagusa/me.png
    - assets/images/flagusa/md.png
    - assets/images/flagusa/ma.png
    - assets/images/flagusa/mi.png
    - assets/images/flagusa/mn.png
    - assets/images/flagusa/ms.png
    - assets/images/flagusa/mo.png
    - assets/images/flagusa/mt.png
    - assets/images/flagusa/ne.png
    - assets/images/flagusa/nv.png
    - assets/images/flagusa/nh.png
    - assets/images/flagusa/nj.png
    - assets/images/flagusa/nm.png
    - assets/images/flagusa/ny.png
    - assets/images/flagusa/nc.png
    - assets/images/flagusa/nd.png
    - assets/images/flagusa/oh.png
    - assets/images/flagusa/ok.png
    - assets/images/flagusa/or.png
    - assets/images/flagusa/pa.png
    - assets/images/flagusa/ri.png
    - assets/images/flagusa/sc.png
    - assets/images/flagusa/sd.png
    - assets/images/flagusa/tn.png
    - assets/images/flagusa/tx.png
    - assets/images/flagusa/ut.png
    - assets/images/flagusa/vt.png
    - assets/images/flagusa/va.png
    - assets/images/flagusa/wa.png
    - assets/images/flagusa/wv.png
    - assets/images/flagusa/wi.png
    - assets/images/flagusa/wy.png
    # Música do jogo
    - assets/songs/musica.mp3
    - assets/songs/som_botao.mp3
