name: geolearn
description: "A new Flutter project."

# Impede que o pacote seja publicado acidentalmente no pub.dev
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

# Define a versão e o número de build do projeto
version: 1.0.0+1

# Define o ambiente e a versão mínima do SDK
environment:
  sdk: ^3.6.0

# Dependências principais do projeto
dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  translator: 1.0.3+1
  audioplayers: ^6.1.2

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recomendações de lint para boas práticas
  flutter_lints: ^5.0.0

# Configuração específica do Flutter
flutter:
  uses-material-design: true # Habilita ícones padrão do Material Design

  # Seção de assets (imagens e outros arquivos)
  assets:
    - assets/images/terra.png
    - assets/images/mountain.png
    - assets/images/paises.png
    - assets/images/bandeiras.png
    - assets/images/estados.png
    - assets/images/brasil.png
    - assets/images/estados-unidos.png
    - assets/images/alemanha.png
    # Assets dos estados brasileiros
    - assets/images/flagsbr/ac.png
    - assets/images/flagsbr/al.png
    - assets/images/flagsbr/ap.png
    - assets/images/flagsbr/am.png
    - assets/images/flagsbr/bh.png
    - assets/images/flagsbr/ce.png
    - assets/images/flagsbr/df.png
    - assets/images/flagsbr/es.png
    - assets/images/flagsbr/go.png
    - assets/images/flagsbr/ma.png
    - assets/images/flagsbr/mt.png
    - assets/images/flagsbr/mg.png
    - assets/images/flagsbr/pa.png
    - assets/images/flagsbr/pb.png
    - assets/images/flagsbr/pr.png
    - assets/images/flagsbr/pe.png
    - assets/images/flagsbr/pi.png
    - assets/images/flagsbr/rj.png
    - assets/images/flagsbr/rn.png
    - assets/images/flagsbr/rs.png
    - assets/images/flagsbr/ro.png
    - assets/images/flagsbr/rr.png
    - assets/images/flagsbr/sc.png
    - assets/images/flagsbr/sp.png
    - assets/images/flagsbr/se.png
    - assets/images/flagsbr/to.png
    # Assets dos estados alemães
    - assets/images/flagsal/bw.png
    - assets/images/flagsal/by.png
    - assets/images/flagsal/be.png
    - assets/images/flagsal/bb.png
    - assets/images/flagsal/hb.png
    - assets/images/flagsal/hh.png
    - assets/images/flagsal/he.png
    - assets/images/flagsal/mv.png
    - assets/images/flagsal/ni.png
    - assets/images/flagsal/nw.png
    - assets/images/flagsal/rp.png
    - assets/images/flagsal/sl.png
    - assets/images/flagsal/sn.png
    - assets/images/flagsal/st.png
    - assets/images/flagsal/sh.png
    - assets/images/flagsal/th.png
    #musica game
    - assets/songs/musica.mp3
    - assets/songs/som_botao.mp3